### ISSUE TITLE
Firebase instructions not complete.

### ISSUE THREAD

**Issue by damnabit** [taoong/mia-empathy#4]
Following the instructions for connecting your own database, after step 5; updating the Firebase SDK snippet in the /src/Firebase.js file and running the app it builds and loads successfully.

I even see very briefly the main prompt for the session, then it fails giving the error in the console:

`The project empathy2 does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database.`

I will work through a full flow for setting up Firebase on our end and send you a pull request.

**Comment by taoong** [comment]
This points out something I overlooked - the readme includes instructions for setting up a Firestore database (which the error message is complaining about) but this is in the section for accessing the admin panel, when it should clearly be in connecting your own database.
